################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:3001/api/v1

### GET ONE ACTIVITY ###
GET {{endpoint}}/activity/2

### search by keyword / zip_code ###
#returns a list of activity cards
POST {{ endpoint }}/activity/search
content-type: application/json

{
    "keyword": "%",
    "zip_code": "75%"
}

### Register an organism ###
POST {{ endpoint }}/organism/register
Content-Type: application/json

{
        "email": "test19@test.com",
        "name": "Organization test register",
        "password": "Tests1234!",
        "confirm_password" : "Tests1234!",
        "description": "description of organization",
        "contact_email": "test19@test.com",
        "phone_number": "0724926658"
}

### Login an organization ###
POST {{endpoint}}/organism/login
Content-Type: application/json

{
    "email": "test19@test.com",
    "password": "Tests1234!"
}

### Get profile of my organization ###
GET {{endpoint}}/organism/profile

### Get list of events of my organization ###
GET {{endpoint}}/organism/activities